namespace EdgeTtsSharp.NAudio.Tests;

public class WindowsPlaybackTests
{
    [SetUp]
    public void Setup() { }

    /// <summary>
    /// This test plays the audio locally on Windows.
    /// </summary>
    [Test]
    public async Task TestWindowsPlayback()
    {
        var voice = await EdgeTts.GetVoice("en-US-ChristopherNeural");
        await voice.PlayText(
            "This is a test of audio generated by EdgeTTS. The stream cohesion is tested by comparing the MD5 hash of the stream to a known value. It is expected to encounter slight deviations, but the audio quality should not be affected.");
    }
}